Add validation test to ignore-template
Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>

diff --git a/ignition-template/Makefile b/ignition-template/Makefile
--- a/ignition-template/Makefile
+++ b/ignition-template/Makefile
@@ -18,7 +18,7 @@ WGET := wget --retry-connrefused --no-verbose
 WGET_PATH := $(shell which wget || echo wget-install)
 
 .PHONY: all
-all: site-env common-env
+all: setup site-env common-env
 
 write-%:
 	mkdir -p $(TEMP_DIR)
@@ -60,9 +60,17 @@ $(WGET_PATH):
 	$(SUDO) apt-get update && $(SUDO) apt-get -y install wget
 
 .PHONY: build
-build: 
+build:
 	mkdir -p $(BINDIR)
 	@go build -o $(BINDIR)/configgenerator
+
+.PHONY: validation
+validation: all
+	if ! test -z "$$(git status --porcelain)"; then \
+		echo "ERROR: git status is not clean"; \
+		git status; \
+		exit 1; \
+	fi
 
 .PHONY: clean
 clean:
